
<div id="breadcrum-inner-block">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 text-center">
        <div class="breadcrum-inner-header">
          <h1>Privacy and Policy </h1>
          <a href="<?=base_url()?>">Home</a> <i class="fa fa-circle"></i> <a href="javascript:void(0)"><span>Privacy and Policy </span></a> </div>
      </div>
    </div>
  </div>
</div>
 <div class="container">
    <div class="row">
        <p style="margin-top:50px">At BNG, we collect and manage user data according to the following Privacy Policy, with the goal of incorporating our company values: transparency, accessibility, sanity, usability. This document is part of BNG&rsquo;s&nbsp;<a href="https://go2bng.com/terms/" target="_blank" rel="noopener">Terms of Service</a>, and by using&nbsp;<a href="https://go2bng.com/" target="_blank" rel="noopener">go2bng.com</a>&nbsp;(the &ldquo;Website&rdquo;), you agree to the terms of this Privacy Policy and the Terms of Service. Please read the Terms of Service in their entirety, and refer to those for definitions and contacts.</p>
        <h3>(a)&nbsp;<strong>Data Collected</strong></h3>
        <p>We collect anonymous data from every visitor of the Website to monitor traffic and fix bugs. For example, we collect information like web requests, the data sent in response to such requests, the Internet Protocol address, the browser type, the browser language, and a timestamp for the request.</p>
        <p>We ask you to log in and provide certain personal information (such as your name and email address) in order to be able to save your profile and the documents and comments associated with it. In order to enable these or any other login based features, we use cookies to store session information for your convenience. You can block or delete cookies and still be able to use BNG, although if you do you will then be asked for your username and password every time you log in to the&nbsp;<a href="https://go2bng.com/" target="_blank" rel="noopener">Website</a>. In order to take advantage of certain features of the Website, you may also choose to provide us with other personal information, such as your picture or personal&nbsp;<a href="https://go2bng.com/" target="_blank" rel="noopener">Website</a>, but your decision to utilize these features and provide such data will always be voluntary.</p>
        <p>You are able to view, change and remove your data associated with your profile. Should you choose to delete your account, please contact us at&nbsp;<a href="mailto:support@go2bng.com">support@go2bng.com</a>, and we will follow up with such request as soon as possible.</p>
        <p>Minors and children should not use BNG. By using the&nbsp;<a href="https://go2bng.com/" target="_blank" rel="noopener">Website</a>, you represent that you have the legal capacity to enter into a binding agreement.</p>
        <h3>(b)&nbsp;<strong>Use of the Data</strong></h3>
        <p>We only use your personal information to provide you the BNG services or to communicate with you about the services or the Website.</p>
        <p>With respect to any documents you may choose to upload to BNG, we take the privacy and confidentiality of such documents seriously. We encrypt all documents, and permanently delete any redacted edits you make to documents. If you choose to make a document public, we recommend you redact any and all references to people and addresses, as we can&rsquo;t protect public data and we are not responsible for any violation of privacy law you may be liable for.</p>
        <p>We employ industry standard techniques to protect against unauthorized access of data about you that we store, including personal information.</p>
        <p><strong>We do not share personal information you have provided to us without your consent, unless:</strong></p>
        <p>&ndash; doing so is appropriate to carry out your own request;<br />&ndash; we believe it&rsquo;s needed to enforce our Terms of Service, or that is legally required;<br />&ndash; we believe it&rsquo;s needed to detect, prevent or address fraud, security or technical issues;<br />&ndash; otherwise protect our property, legal rights, or that of others.</p>
        <p>BNG is operated from the United States. If you are visiting the Website from outside the U.S., you agree to any processing of any personal information you provide us according to this policy.</p>
        <p>BNG may contact you, by email or other means. For example, BNG may send you promotional emails relating to BNG or other third parties BNG feels you would be interested in, or communicate with you about your use of the BNG website. BNG may also use technology to alert us via a confirmation email when you open an email from us. You can modify your email notification preferences by clicking the appropriate link included in the footer of email notifications. If you do not want to receive email from BNG, please opt out of receiving emails at the bottom of any BNG emails.</p>
        <h3>(c)&nbsp;&nbsp;<strong>Sharing of Data</strong></h3>
        <p>We don&rsquo;t share your personal information with third parties. Only aggregated, anonymized data is periodically transmitted to external services to help us improve the BNG Website and service. We currently use Google Analytics (traffic analysis, SEO optimization), Mailchimp (mailing list management), Zendesk (email support) and Chartbeat (analytics). We listed below what data these third parties extract exactly. Feel free to check out their own Privacy Policies to find out more.</p>
        <p>&ndash; Google Analytics: anonymous (ad serving domains, browser type, demographics, language settings, page views, time/date), pseudonymous (IP address)</p>
        <p>We also use social buttons provided by services like Twitter, Google+, LinkedIn and Facebook. Your use of these third party services is entirely optional. We are not responsible for the privacy policies and/or practices of these third party services, and you are responsible for reading and understanding those third party services&rsquo; privacy policies.</p>
        <p>We employ and contract with people and other entities that perform certain tasks on our behalf and who are under our control (our &ldquo;Agents&rdquo;). We may need to share personal information with our Agents in order to provide products or services to you. Unless we tell you differently, our Agents do not have any right to use Personal Information or other information we share with them beyond what is necessary to assist us. You hereby consent to our sharing of Personal Information with our Agents.</p>
        <p>We may choose to buy or sell assets. In these types of transactions, user information is typically one of the transferred business assets. Moreover, if we, or substantially all of our assets, were acquired, or if we go out of business or enter bankruptcy, user information would be one of the assets that is transferred or acquired by a third party. You acknowledge that such transfers may occur, and that any acquirer of us or our assets may continue to use your personal information as set forth in this policy.</p>
        <h2><strong><u>BNG GDPR Privacy Notice</u></strong><u></u></h2>
        <p>If you are located in the European Union (&ldquo;EU&rdquo;), United Kingdom, Lichtenstein, Norway, or Iceland, you may have additional rights under the EU General Data Protection Regulation (the &ldquo;GDPR&rdquo;) with respect to your Personal Data, as outlined below.</p>
        <p>For this GDPR Privacy Notice, we use the terms &ldquo;Personal Data&rdquo; and &ldquo;processing&rdquo; as they are defined in the GDPR, but &ldquo;Personal Data&rdquo; generally means information that can be used to individually identify a person, and &ldquo;processing&rdquo; generally covers actions that can be performed in connection with data, such as collection, use, storage and disclosure.&nbsp; BNG, Inc. (&ldquo;BNG&rdquo;) will be the controller of your Personal Data processed in connection with the Services, except that we may also process Personal Data of our customers&rsquo; end users or employees in connection with our provision of services to such customers, in which case we are the processor of Personal Data and the customer is the controller. &nbsp;For more information about your data rights and processing activities where we are the controller, please contact us at&nbsp;<a href="mailto:privacy@go2bng.com" target="_blank" rel="noopener">privacy@go2bng.com</a>. For more information about your data rights and processing activities where we are the processor, please contact the controller party in the first instance.</p>
        <p>Where applicable, this GDPR Privacy Notice is intended to supplement, and not replace, our existing privacy policy).&nbsp; If there are any conflicts between this GDPR Privacy Notice and our Privacy Policy, the policy or portion that is more protective of Personal Data shall control to the extent of such conflict.&nbsp; If you have any questions about this notice or whether any of the following applies to you, please contact us at&nbsp;<a href="mailto:privacy@go2bng.com" target="_blank" rel="noopener">privacy@go2bng.com</a>.</p>
        <p><strong><u>How We Process Personal Data:</u></strong><br />We will only process your Personal Data if we have a lawful basis for doing so. Lawful bases for processing include consent, contractual necessity and our &ldquo;legitimate interests&rdquo; or the legitimate interest of others, as further described below. In some cases, we process Personal Data based on the consent you expressly grant to us at the time we collect such Personal Data.&nbsp; When we process Personal Data based on your consent, it will be expressly indicated to you at the point and time of collection. From time to time, we may also need to process Personal Data to comply with a legal obligation, if it is necessary to protect the vital interests of you or other data subjects, or if it is necessary for a task carried out in the public interest.</p>
        <p><strong><u>What Personal Data Do We Collect From You and How Do We Use Your Personal Data?</u></strong><br />We collect Personal Data about you when you provide such Personal Data directly to us, when third parties such as our business partners or service providers provide us with Personal Data about you, or when Personal Data about you is automatically collected in connection with your use of our Services.</p>
        <p><u>Information we collect directly from you</u>:</p>
        <p>We receive certain Personal Data directly from you when you provide us with such Personal Data, including without limitation the following:</p>
        <p>&ndash; First name<br />&ndash; Last name<br />&ndash; Email address<br />&ndash; Mailing address<br />&ndash; Telephone number<br />&ndash; Country<br />&ndash; Job Title</p>
        <p>We collect and process these categories of Personal Data as a matter of contractual necessity so that we can provide the Services to you in accordance with our&nbsp;<a href="https://go2bng.com/terms/">Terms of Service</a>.&nbsp; For example, we cannot open an account for you if you do not provide us with your first and last name.&nbsp; When we process Personal Data due to contractual necessity, failure to provide such Personal Data will result in your inability to use some or all portions of the Services that require such Personal Data.</p>
        <p>We may also collect user content from you when you provide it to us.&nbsp; For example, the Services allow you to provide us with comments, posts, and user writing samples that you submit, and you may choose to provide Personal Data (such as your name) in such content. By sharing this user content in a public forum, you are choosing to disclose any Personal Data included in such content, and we do not have control over your decision.&nbsp; We process user content, including any Personal Data included in any such user content, on the basis of our legitimate business interest in providing you with the Services.</p>
        <p>We also use the Personal Data we collect directly from you to operate, improve, understand and personalize our Services based on our legitimate business interest in operating our Services in a way that benefits us and our users.&nbsp; For example, we use the Personal Data to:</p>
        <p>&ndash; Create and manage user profiles<br />&ndash; Communicate with you about the Services<br />&ndash; Contact you about Service announcements, updates or offers<br />&ndash; Provide support and assistance for the Services<br />&ndash; Personalize website content and communications based on your preferences<br />&ndash; Meet contract or legal obligations<br />&ndash; Respond to user inquiries<br />&ndash; Fulfill user requests<br />&ndash; Comply with our legal or contractual obligations<br />&ndash; Resolve disputes<br />&ndash; Protect against or deter fraudulent, illegal or harmful actions<br />&ndash; Enforce our&nbsp;<a href="https://go2bng.com/terms/">Terms of Service</a></p>
        <p><u>Information we receive from third party sources:</u><strong>&nbsp;&nbsp;</strong>Some third parties provide us with Personal Data about you, such as the following:</p>
        <p><strong>&ndash; Account information for third party services:</strong>&nbsp;If you interact with a third party service when using our Services, such as if you use a third party service to log-in to our Services (e.g., Facebook Connect), or if you share content from our Services through such third party service, the applicable third party service will send us certain Personal Data (specifically your first name, ID, token and profile picture URL) if the third party service and your account settings allow such sharing. Specifically, this Personal Data permits us to create and manage user profiles and sync your progress when you connect to Facebook through the Services. The Personal Data we receive will depend on the policies and your account settings with the applicable third party service.&nbsp; We process this Personal Data based on our legitimate business interest of personalizing and optimizing the Services to improve user experience.</p>
        <p><strong>&ndash; Information from our advertising partners:</strong>&nbsp;We receive information about you from some of our service providers (e.g., LinkedIn) who assist us with marketing or promotional services related to how you interact with our websites, applications, products, services, advertisements or communications. We process this Personal Data based on our legitimate business interest in providing direct marketing about our products and services.</p>
        <p><u>Information we automatically collect when you use our Services</u>:&nbsp;<strong>&nbsp;</strong>Some Personal Data is automatically collected when you use our Services, such as the following:</p>
        <p>&ndash; IP address<br />&ndash; Device identifiers<br />&ndash; Web browser information<br />&ndash; Page view statistics<br />&ndash; Browsing history<br />&ndash; Usage information<br />&ndash; Cookies and other tracking technologies (e.g. web beacons, pixel tags, SDKs, etc.)<br />&ndash; Location information (e.g. IP address, zip code)<br />&ndash; Log data (e.g. access times, hardware and software information)</p>
        <p>We process this Personal Data based on the following legitimate business interests:</p>
        <p>&ndash; Network security<br />&ndash; Personalization of web content<br />&ndash; Evaluation of quality of writing to consider engagement<br />&ndash; Web analytics<br />&ndash; Provision of rewards<br />&ndash; Administrative matters</p>
        <p>In collecting the Personal Data, we sometimes use &ldquo;cookies&rdquo; and other tracking technologies (e.g., web beacons and pixel tags). Cookies allow us to recognize your browser or device and &ldquo;remember&rdquo; your browser during subsequent visits for purposes of functionality, preferences, and website performance, and they also tell us how and when pages and features in our Services are visited and by how many people. The Services use the following cookies:</p>
        <p><strong>&ndash; Essential Cookies.</strong>&nbsp;Essential cookies are required for providing you features or services that you have requested. For example, certain cookies enable you to log into secure areas of our Site. Disabling these cookies may make certain features and services unavailable.</p>
        <p><strong>&ndash; Functionality Cookies.</strong>&nbsp;Functional cookies are used to record your choices and settings regarding our Services, maintain your preferences over time, and recognize you when you return to our Services. These cookies help us to personalize our content for you, greet you by name and remember your preferences (for example, your choice of language or region).</p>
        <p><strong>&ndash; Performance/Analytical Cookies.</strong>&nbsp;Performance/analytical cookies allow us to understand how visitors use our Site and Services such as by collecting information about the number of visitors to the Site, what pages visitors view on our Site, and how long visitors are viewing pages on the Site. Performance/analytical cookies also help us measure the performance of our advertising campaigns in order to help us improve our campaigns and the Services&rsquo; content for those who engage with our advertising.</p>
        <p><strong>&ndash; Retargeting/Advertising Cookies.</strong>&nbsp;Retargeting/advertising cookies collect data about your online activity and identify your interests so that we can provide advertising that we believe is relevant to you.</p>
        <p>Most browsers automatically accept cookies but have an option for blocking or deleting cookies, which will prevent your browser from accepting new cookies, as well as (depending on the sophistication of your browser software) allow you to decide on acceptance of each new cookie in a variety of ways. You can usually access these options through the &ldquo;Settings&rdquo; or similar menu in your browser.&nbsp; For more information about cookies, including how to see what cookies have been set and how to manage and delete cookies, visit www.aboutcookies.org or www.allaboutcookies.org.&nbsp; Please note that if you block or delete cookies, some portions of the Services may not work properly. In some cases, cookies may enable us to aggregate certain information with other Personal Data we collect and hold about you.</p>
        <p><u>Other uses of Personal Data:</u>&nbsp; In addition to the uses set forth above, we may also process the Personal Data we collect on the basis of the following legitimate business interests.</p>
        <p>&ndash; Operation and improvement of our business, products and services<br />&ndash; Marketing of our products and services<br />&ndash; Provision of customer support<br />&ndash; Protection from fraud or security threats<br />&ndash; Compliance with legal obligations<br />&ndash; Completion of corporate transactions</p>
        <p><strong><u>How and With Whom Do We Share Your Data?</u></strong><br />We share Personal Data with vendors, third party service providers and agents who work on our behalf and provide us with services related to the purposes described in this Privacy Policy or our&nbsp;<a href="https://go2bng.com/terms/">Terms of Service</a>. These parties include:</p>
        <p>&ndash; Analytics service providers<br />&ndash; Staff augmentation and contract personnel<br />&ndash; Hosting service providers</p>
        <p>We also share Personal Data when necessary to complete a transaction initiated or authorized by you or provide you with a product or service you have requested.&nbsp; In addition to those set forth above, these parties also include:</p>
        <p>&ndash; Other users (where you post information publicly or as otherwise necessary to effect a transaction initiated or authorized by you through the Services)<br />&ndash; Social media services (if you interact with them through your use of the Services)<br />&ndash; Third party business partners who you access through the Services<br />&ndash; Other parties authorized by you</p>
        <p>We also share Personal Data when we believe it is necessary to:</p>
        <p>&ndash; Comply with applicable law or respond to valid legal process, including from law enforcement or other government agencies<br />&ndash; Protect us, our business or our users, for example to enforce our terms of service, prevent spam or other unwanted communications and investigate or protect against fraud<br />&ndash; Maintain the security of our products and services</p>
        <p>We also share Personal Data with third parties when you give us consent to do so.</p>
        <p>Furthermore, if we choose to buy or sell assets, user information is typically one of the transferred business assets. Moreover, if we, or substantially all of our assets, were acquired, or if we go out of business or enter bankruptcy, user information would be one of the assets that is transferred or acquired by a third party, and we would share Personal Data with the party that is acquiring our assets based on our legitimate business interest of being able to provide you with continued services. You acknowledge that such transfers may occur, and that any acquirer of us or our assets may continue to use your Personal Information as set forth in this policy.</p>
        <p><strong><u>How Long Do We Retain Your Personal Data?</u></strong><strong><br /></strong>We retain Personal Data about you for as long as you have an open account with us or as otherwise necessary to provide the Services to you and improve the Services for all users generally. &nbsp;In some cases we retain Personal Data for longer, if doing so is necessary to comply with our legal obligations, resolve disputes or collect fees owed, or is otherwise permitted or required by applicable law, rule or regulation. Afterwards, we retain some information in a depersonalized or aggregated form but not in a way that would identify you personally.</p>
        <p><strong><u>What Security Measures Do We Use?</u></strong><br />We seek to protect Personal Data using appropriate technical and organizational measures based on the type of Personal Data and applicable processing activity.</p>
        <p><strong><u>Personal Data of Children</u></strong><strong>:<br /></strong>We do not knowingly collect or solicit Personal Data from anyone in the EU, United Kingdom, Lichtenstein, Norway, or Iceland under the age of 16.&nbsp; If you are under 16, please do not attempt to register for the Services or send any Personal Data about yourself to us.&nbsp; If we learn that we have collected Personal Data from a child under age 16, we will delete that information as quickly as possible. If you believe that a child under 16 may have provided us Personal Data, please contact us at&nbsp;<a href="mailto:privacy@go2bng.com">privacy@go2bng.com</a>.</p>
        <p><strong><u>What Rights Do You Have Regarding Your Personal Data?</u></strong><br />You have certain rights with respect to your Personal Data, including those set forth below.&nbsp; For more information about these rights, or to submit a request, please email&nbsp;<a href="mailto:privacy@go2bng.com">privacy@go2bng.com</a>. Please note that in some circumstances, we may not be able to fully comply with your request, such as if it is frivolous or extremely impractical, if it jeopardizes the rights of others, or if it is not required by law, but in those circumstances, we will still respond to notify you of such a decision.&nbsp; In some cases, we may also need to you to provide us with additional information, which may include Personal Data, if necessary to verify your identity and the nature of your request.</p>
        <p><strong>&ndash; Access</strong>: You can request more information about the Personal Data we hold about you and request a copy of such Personal Data. You can also access certain of your Personal Data by emailing us at privacy@go2bng.com.</p>
        <p><strong>Rectification</strong>: If you believe that any Personal Data we are holding about you is incorrect or incomplete, you can request that we correct or supplement Personal Data by emailing us at&nbsp;<a href="mailto:privacy@go2bng.com">privacy@go2bng.com</a>.</p>
        <p><strong>&ndash; Erasure</strong>: You can request that we erase some or all of your Personal Data from our systems.</p>
        <p><strong>&ndash; Withdrawal of Consent</strong>: If we are processing your Personal Data based on your consent (as indicated at the time of collection of such data), you have the right to withdraw your consent at any time. Please note, however, that if you exercise this right, you may have to then provide express consent on a case-by-case basis for the use or disclosure of certain of your Personal Data, if such use or disclosure is necessary to enable you to utilize some or all of our Services.</p>
        <p><strong>&ndash; Portability</strong>: You can ask for a copy of your Personal Data in a machine-readable format.&nbsp; You can also request that we transmit the data to another controller where technically feasible.</p>
        <p><strong>&ndash; Objection</strong>: You can contact us to let us know that you object to the further use or disclosure of your Personal Data for certain purposes, such as for direct marketing purposes.</p>
        <p><strong>&ndash; Restriction of Processing</strong>: You can ask us to restrict further processing of your Personal Data.</p>
        <p><strong>&ndash; Right to File Complaint</strong>: You have the right to lodge a complaint about our practices with respect to your Personal Data with the supervisory authority of your country or EU Member State.</p>
        <p><strong><u>What if You Have Questions Regarding your Personal Data?</u></strong><br />If you have any questions about this GDPR Privacy Notice or our data practices generally, please contact us using the following information:</p>
</div>
</div>